### ISSUE TITLE
UI: Resizable "edit policy setting" dialog

### ISSUE THREAD

**Issue by ThiefMaster** [Fleex255/PolicyPlus#11]
Again, not sure if this is possible at all or if it's up to windows to show this dialog (but maybe it can be modified nonetheless?) - but it would be nice if that dialog could be resized, especially to avoid having horizontal scrollbars like in the example below.

![image](https://user-images.githubusercontent.com/179599/32989861-e016b6a0-cd1e-11e7-84f2-77bb985e83a0.png)

Edit: Actually, I noticed that this dialog *is* resizable in the original GPE, at least on Win10

**Comment by Fleex255** [comment]
Implemented in https://github.com/Fleex255/PolicyPlus/commit/8a3fc2e3eea7f43887036f437e8c276449b05d45; the Debug build has been updated. Please let me know whether the changes are working as expected. Thanks for the suggestion!

The reason for the horizontal scrollbar appearing was that policies with many elements filled the extra options panel and necessitated a vertical scrollbar, which reduced the client area of the panel. Since the size of the element controls was fixed at their creation, they remained the same size even though the available space decreased, so they overflowed the panel and created the horizontal bar. Now they are all sized correctly after populating the panel and resized whenever the form is.

**Comment by ThiefMaster** [comment]
works fine, ty!
