### ISSUE TITLE
Error Message: Missing PReg signature; JIT debugging required

### ISSUE THREAD

**Issue by SonnyMD** [Fleex255/PolicyPlus#13]
Hi all!

First, I'd like to say that PolicyPlus is a great tool, thank you for making it happen.

Two, I'm a novice when it comes to scripts, powershell, or anything that approaches coding; I am comfortable with modding the Registry for some reason though.

History:  PolicyPlus was working fine until I turned something on or off in Windows 10; thus I think the issue lies with me and not your program.  I tried to resolve things on my own before bothering anyone here, but after 6 hours I thought I'd better drop you all a line. 

So here is how everything works now (it ran perfectly before)

As soon as I launch the program I get: 

![image](https://user-images.githubusercontent.com/32553137/33147750-cc7deda0-cf7d-11e7-8f35-f597d8f63489.png)

Once I click on okay I get the following message:

![image](https://user-images.githubusercontent.com/32553137/33147827-37d39f64-cf7e-11e7-86da-4b78e7c963fb.png)

Which at the bottom of the details box, says I need to enable/configure JIT debugging - for which I am at total loss on how to do.  

![image](https://user-images.githubusercontent.com/32553137/33148046-201f06d2-cf7f-11e7-9580-4dbc8a0d99bd.png)

Can anyone help a simp like me?

**Comment by Fleex255** [comment]
Ah, the message about JIT debugging is confusing, sorry about that. That style of error report dialog is produced from the .NET Framework when an unhandled error occurs in an application. The instructions about enabling debugging are intended for developers. Thank you for providing all errors, because the dialog does also show the proximate cause: one of the POL files (which store the Registry-based policy data) has become corrupt and no longer has the correct signature of `PReg`.

The POL files for the local GPO are stored in `C:\Windows\System32\GroupPolicy\*\Registry.pol`, where `*` is `Machine` or `User`. You can remove or rename the POL file to reset your GPO (Policy Plus will recreate it), or if you upload them somewhere, I'd be happy to try to repair them for you and save customizations you already made. Alternatively, you can convert the policy settings in your Registry back into POL files with this procedure:

1. Move those POL files somewhere else so they won't trip up Policy Plus.
2. Use *File | Open Policy Resources* to open the default Local Registry branch for both sections.
3. Use *Share | Export POL* to save the Computer policies to a temporary POL file somewhere on disk.
4. Repeat step 3, but with the User section. Make sure to save the policies to a different POL file.
5. Use *Open Policy Resources* to open the Local GPO for both sections.
6. Use *Share | Import POL* to load the Computer policies from the temporary POL created in step 3.
7. Repeat step 6, but with the User section.
8. Use *File | Save Policies* to commit the changes to disk.

**Comment by SonnyMD** [comment]
Thank you so much!

Your instructions are so clear I will brave things and give it a shot on my first. 
If success somehow eludes me I will definitely take you up on your kind and generous offer.

But first, it's off to Thanksgiving celebrations with my extended family!  
Happy Thanksgiving to you and yours!

**Comment by SonnyMD** [comment]
It occurred to me I did not mention my system/OS specs (duh!)

Windows 10, v.1709, 64-bit, x64-based processor

**Comment by SonnyMD** [comment]
Alright, looks like things are working as they ought to.

Since the O/S is Win10-HE, I manually save each adjustment made and then reboot to see if it has "held" in the program, which it did (yay!).  

Based on what you said about HE I went back to the item I edited in PolicyPlus and got the registry location from the Element Inspector (below).
![image](https://user-images.githubusercontent.com/32553137/33225339-39dd9712-d12a-11e7-9612-02dda50601be.png)
After which, I opened up my registry using O&O's RegEditor and found the registry key in HKLM, which confirmed the edit.
![image](https://user-images.githubusercontent.com/32553137/33225354-962e3a58-d12a-11e7-9880-59505af87c79.png)

Please let me know if I missed something.

Again, thank you for your kind help. 

Am I correct in understanding that you want to develop this into a commercial product?

**Comment by Fleex255** [comment]
Awesome, looks like we got this sorted out!

I plan on keeping Policy Plus free and open-source forever so that the power of Group Policy can be brought to all Windows users. I would be open to the possibility of integrating Policy Plus into a larger solution intended for companies, though.

Thanks for your interest in Policy Plus! If there's anything I can help with, just let me know. 😃
