### ISSUE TITLE
Policy definitions could not be loaded: An item with the same key has already been added

### ISSUE THREAD

**Issue by dermeister0** [Fleex255/PolicyPlus#15]
I have a problem on Windows 10 Insider Preview. Somehow system policy became duplicated.

The standard gpedit shows errors, but works:

```
---------------------------
Administrative Templates
---------------------------
Namespace 'Microsoft.Policies.Sensors.WindowsLocationProvider' is already defined as the target namespace for another file in the store.



File C:\WINDOWS\PolicyDefinitions\Microsoft-Windows-Geolocation-WLPAdm.admx, line 5, column 110
---------------------------
OK
---------------------------
```

```
---------------------------
Administrative Templates
---------------------------
Invalid value '$(string.UploadUserActivities _Help)' for attribute explainText.



File C:\WINDOWS\PolicyDefinitions\OSPolicy.admx, line 35, column 234
---------------------------
OK
---------------------------
```

Policy Plus shows error and does not load data:

```
---------------------------
Policy Plus
---------------------------
Policy definitions could not be loaded: An item with the same key has already been added.
---------------------------
OK
---------------------------
```

**Comment by Fleex255** [comment]
Sorry, I only just got around to creating a Windows Insider VM. I'm unable to reproduce this on build 17110. Could you please upload an archive of `C:\Windows\PolicyDefinitions`?

**Comment by mnaiman** [comment]
https://support.microsoft.com/en-us/help/3077013/microsoft-policies-sensors-windowslocationprovider-is-already-defined

**Comment by Fleex255** [comment]
This behavior is greatly improved in https://github.com/Fleex255/PolicyPlus/commit/d5bcc597135b78b97f4f655a83d34da02e706b53. Now instead of bailing on the whole folder's load, Policy Plus keeps track of the problems and displays them after the rest of the ADMX files load successfully.

The [dev build](https://s3-us-west-2.amazonaws.com/policy-plus/PolicyPlusDev.exe) has been updated; please try it and let me know if it's helpful.
