### ISSUE TITLE
Project abandoned? 

### ISSUE THREAD

**Issue by MrX-at-GitHub** [Fleex255/PolicyPlus#18]
Hi,

Great little program. Haven't seen any update to it so is it abandoned?

**Comment by Fleex255** [comment]
Hi! There hasn't been a lot of feature work recently because I've been pretty busy with things in real life. Nevertheless, I am still open to any specific feature requests (and especially bug reports - I would do my best to handle those quickly). I do plan to continue expanding its functionality in the vaguely near future. Thanks for trying Policy Plus!
