### ISSUE TITLE
Import/Export reg to raw pol

### ISSUE THREAD

**Issue by joeparkerz** [Fleex255/PolicyPlus#2]
Can you add this? 
Say if I have a reg file containing GPO and I want to import it in the RAW pol or the other way around.

Thanks.

**Comment by Fleex255** [comment]
Yes, this would be a useful feature; I will see about implementing it. I'm thinking of adding "Import REG" and "Export REG" entries to the Share menu of the main form, since I could see that functionality (especially export) being helpful even outside the raw editor. Then again, exporting just one of the branches (which are only shown in the raw editor) could be useful. I'll have to do some thinking about that - additional commentary is welcome.

**Comment by joeparkerz** [comment]
Indeed this would add even more capability to an otherwise excellent utility.

**Comment by Fleex255** [comment]
REG support implemented in https://github.com/Fleex255/PolicyPlus/commit/18d1d86a23b03d83b91252d81c3a1950db11525d, Edit Raw POL integration added in https://github.com/Fleex255/PolicyPlus/commit/759c652f7d6c47a4701630f333927cd25331e18c. If you have Visual Studio, you can compile the current source to test it; if not, let me know and I'll put up a debug build. Thanks for the feature suggestion!

**Comment by Fleex255** [comment]
[Here is a Debug build](https://s3-us-west-2.amazonaws.com/policy-plus/PolicyPlusDev.exe) that includes the changes. If these do the job, I think we're ready to release them to the suggested build.
