### ISSUE TITLE
Ignore dictionary duplicate collisions

### ISSUE THREAD

**Issue by Ceiridge** [Fleex255/PolicyPlus#27]
After downloading the admx files, I had some problems with duplicates when loading the entire `PolicyDefinitions` folder, since it would always crash with a .NET Error: `An item with the same key has already been added`.

The default group policy editor ignores such duplicates, and that's what I quickly did with dnspy (because I'm too lazy to recompile the entire project).
To improve this, I recommend to fix this in the `AdmxBundle` file, method `AddSingleAdmx`.

This is what I did (too lazy for a pull request):

Original:
```
' Stage the raw ADMX info for BuildStructures
RawCategories.AddRange(admx.Categories)
RawProducts.AddRange(admx.Products)
RawPolicies.AddRange(admx.Policies)
RawSupport.AddRange(admx.SupportedOnDefinitions)
SourceFiles.Add(admx, adml)
```

Improved with duplicate checking:
```
foreach(var category in admx.Categories) {
	if(!this.RawCategories.Exists(item => item.ID == category.ID))
		this.RawCategories.Add(category);
}

foreach(var product in admx.Products) {
	if(!this.RawProducts.Exists(item => item.ID == product.ID))
		this.RawProducts.Add(product);
}

foreach(var policy in admx.Policies) {
	if(!this.RawPolicies.Exists(item => item.ID == policy.ID))
		this.RawPolicies.Add(policy);
}

foreach(var support in admx.SupportedOnDefinitions) {
	if(!this.RawSupport.Exists(item => item.ID == support.ID))
		this.RawSupport.Add(support);
}

if (!this.SourceFiles.ContainsKey(admx)) {
	this.SourceFiles.Add(admx, value);
}
```

**Keep in mind that your source code could have changed. This is what I entered in dnspy, in the latest release.**

These changes allowed me to completely use the policy editor.

**Comment by Ceiridge** [comment]
Oh, and keep in mind that my code is in C#.

**Comment by Fleex255** [comment]
I'm sorry, I'm not sure exactly what conditions trigger this error for you. If I duplicate an ADMX/ADML pair (e.g. copying `ActiveXInstallService.admx` to `ActiveXInstallService_.admx` without changing the contents), I get an error like this from the Local Group Policy Editor:

![image](https://user-images.githubusercontent.com/4155641/60762688-8b24e680-a02b-11e9-8ee0-238b9bbdba7c.png)

If I edit the duplicated ADMX to change the `namespace` of the `target` element, both Policy Plus and the Local Group Policy Editor create duplicate entries with no error because the items from the different ADMX files have different fully-qualified/unique IDs.

I suspect allowing multiple files to contribute duplicate, potentially different items to a namespace could lead to strange behavior, so I'm hesitant to allow that by default. What actions or set of policies cause this error for you?

**Comment by Ceiridge** [comment]
Strange. Maybe it has something to do with the different language files (German and English) and there it creates a duplicate?
I can only tell that it crashed because of a dictionary error that gets caught by that message box thing.

Because of that, I just fixed that with dnspy, so it's not my problem anymore.
