### ISSUE TITLE
Nothing happens when i click apply

### ISSUE THREAD

**Issue by jduust** [Fleex255/PolicyPlus#30]
The following worked on my desktop that has gpedit and windows 10 pro, but when i tried on my laptop it failed: So i have windows 10 home 64-bit, and need to do [this ](https://stackoverflow.com/questions/23055651/disable-developer-mode-extensions-pop-up-in-chrome)for a custom extension i've made. When i go to edit the key in gpedit.msc (which i installed using the .bat [here](https://www.majorgeeks.com/files/details/add_gpedit_msc_with_powershell.html), it didn't work. It applies, and says it's activated, but when it didn't work once i open google chrome, and when i refresh gpedit it doesn't say it's applied. 

So i tried installing policy plus, and when i edit the key and click apply nothing happens at all. It doesn't even update in the policy plus explorer like it did in gpedit, it just says it's disabled. No error message either. I googled a bit and found someone recommending i deleted all files in the system32/grouppolicy folder, and renamed secpol (renamed it to secpol.msc.old after granting ownership) in system32 folder. Now my system is in danish, and i found 6 instances of secpol.msc, i renamed the once in system 32 folder to old, but still to no luck, i still can't apply my changes in policy plus.

Also there's a "warning" ish yellow triangle on the google policy folders i'm trying to edit, don't know if that means anything, it doesn't give any indication as to what the warning is.

**Comment by Fleex255** [comment]
Ah, I can see how this can be confusing. For policy sources backed by a POL file (like the local Group Policy object), pressing Apply only updates the setting in Policy Plus's memory. To save the POL to disk, you need to use *File | Save Policies*.

Regarding the warning triangle, this icon is shown for policies that aren't actually in a Policies subkey in the Registry. When one of these entries is selected, the middle pane has a paragraph saying "because it is not stored in a Policies section of the Registry, this policy is a preference and will not be automatically undone if the setting is removed."

**Comment by jduust** [comment]
No i get that, but it doesn't even update my changes in policy plus, if i enable a key, or change it's settings and click apply, it doesn't even update it's status in policy plus (still says (disabled), and clicking file -> save policies doesn't change anything because the changes i apply don't even apply to policy plus. 

Maybe this [screenshot ](https://i.imgur.com/nT9Ugyj.png)can help explain my issue. Basically, i edit the key, i press enable, enter a extension id, click apply. When i click apply nothing changes, the window still remains open and it seems like the button does nothing. When i close the window the key is still listed as disabled.

**Comment by Fleex255** [comment]
Oops, sorry I didn't see your comment for a couple days. I think you're running into a recently fixed Policy Plus bug (#29). Does the [dev build](https://s3-us-west-2.amazonaws.com/policy-plus/PolicyPlusDev.exe) work better?

**Comment by PseudonymPatel** [comment]
jduust if you do not click save, neither the ok button or apply do anything.  
Fleex255, I want to hijack this thread to say to remove the apply button or change it to apply+save, otherwise, the apply button confuses people because nothing happens when you press it and you have to click save after you click apply so you might as well hit ok then save, making the apply button useless.

**Comment by jduust** [comment]
> Oops, sorry I didn't see your comment for a couple days. I think you're running into a recently fixed Policy Plus bug (#29). Does the [dev build](https://s3-us-west-2.amazonaws.com/policy-plus/PolicyPlusDev.exe) work better?

Yes, that fixed it, thank you!

**Comment by jduust** [comment]
> jduust if you do not click save, neither the ok button or apply do anything.

Yes, but that's not the issue, it was a bug fixed in the dev build as Fleex225 mentioned.
