### ISSUE TITLE
Cannot Export to REG (After Applying Exploit Protection Settings)

### ISSUE THREAD

**Issue by dennyamarojr** [Fleex255/PolicyPlus#37]
After enable a few settings in Exploit Protection in Microsoft Defender (Windows Defender), cannot export to REG file.

**Comment by Fleex255** [comment]
Hmm, I cannot reproduce this after enabling "use a common set of exploit protection settings" (`Microsoft.Policies.ExploitGuard:ExploitProtection_Name`, the only policy I see in *Windows Components | Microsoft Defender Exploit Guard | Exploit Protection*). What exactly are you trying to enable and what exactly happens when you try to export to a REG file?

**Comment by dennyamarojr** [comment]
I'm using Windows 10 20H2 and in the App and browser control> Exploit protection settings 
I set everything to On by Default and them import the exploit protection available here https://github.com/jdgregson/Windows-10-Exploit-Protection-Settings

After restart the computer, stop working the export REG

**Comment by dennyamarojr** [comment]
![image](https://user-images.githubusercontent.com/36896116/100492457-0aafcb80-30e1-11eb-9f98-3132d9972d13.png)

![image](https://user-images.githubusercontent.com/36896116/100492465-2adf8a80-30e1-11eb-9bef-0150d031069f.png)

**Comment by Fleex255** [comment]
Thank you for the details! It turned out to be possible to reproduce the issue independently of the exploit protection settings: there were some bugs in the handling of list policy elements that clear the list key before adding values. Those are addressed in https://github.com/Fleex255/PolicyPlus/commit/6233795cec5e287400735257f4b2d93648e69307. Please let me know if the [updated dev build](https://s3-us-west-2.amazonaws.com/policy-plus/PolicyPlusDev.exe) fixes the problem.

**Comment by dennyamarojr** [comment]
Will try the new version here and them back to say if fix or not the problem

**Comment by dennyamarojr** [comment]
![image](https://user-images.githubusercontent.com/36896116/100524539-ddf5c580-316d-11eb-9bae-395c85a4d839.png)

**Comment by dennyamarojr** [comment]
additional information, for the users with attack surface reduction rules, if include the 
Block executable files from running unless they meet a prevalence, age, or trusted list criterion - 01443614-cd74-433a-b99e-2ecdc07bfc25

Microsoft Defender block the PolicyPlus to run, you may need add to the exclusion of attack surface reduction rules to run or turn it off when you want to use, changing the value from 1 to 0. in gpedit.msc

Here's a picture
![Screenshot 2020-11-28 113511](https://user-images.githubusercontent.com/36896116/100524578-3200aa00-316e-11eb-997b-651b49d00a7e.jpg)

**Comment by dennyamarojr** [comment]
![image](https://user-images.githubusercontent.com/36896116/100524642-b8b58700-316e-11eb-978a-9dd9e760d504.png)

**Comment by Fleex255** [comment]
Thanks for the info! And of course thank you again for the bug report. I'm glad to see that this seems to be working as intended now.
