### ISSUE TITLE
Local Group Policy Editor and Policy Plus

### ISSUE THREAD

**Issue by KLASSNO** [Fleex255/PolicyPlus#38]
![1](https://user-images.githubusercontent.com/22128293/102783280-7faeb200-43bc-11eb-8d07-fce0660b7453.png)
![2](https://user-images.githubusercontent.com/22128293/102783286-80dfdf00-43bc-11eb-9590-4e1df0f92170.png)

**Comment by Fleex255** [comment]
Thanks for the report! Apparently the real LGPE writes the "off" values of checkbox elements with explicit data when the policy is disabled instead of just deleting the element Registry value. This seems somewhat strange to me since it can make "policy enabled but checkbox unchecked" indistinguishable from "policy disabled" (e.g. in `Microsoft.Policies.ControlPanel:AllowOnlineTips`), but it is what it is.

Policy Plus should faithfully replicate this behavior as of https://github.com/Fleex255/PolicyPlus/commit/8b856ee993faa376a37eef7cb36a69e48e2b4696. Could you please check whether the [updated dev build](https://s3-us-west-2.amazonaws.com/policy-plus/PolicyPlusDev.exe) fixes the problem?

**Comment by KLASSNO** [comment]
Yes, now everything is OK!
