### ISSUE TITLE
"Failed to take control of destination" error

### ISSUE THREAD

**Issue by zdat** [Fleex255/PolicyPlus#42]
After going to Help > Acquire ADMX Files I get a "System.Windows.Forms" error: "Failed to take control of destination".

This happens during the "Unpacking MSI..." stage.

Any help? Thanks.

**Comment by Fleex255** [comment]
Hmm, installing ADMX files appears to work for me on a fresh Windows 10 2004 installation. Which Windows version do you have? Could you double-check that you are logged on as an administrator? (Policy Plus will only ask to elevate if you are.) Are you trying to download the ADMX files to the default location or to somewhere else?

**Comment by zdat** [comment]
Using Windows 7 Home - Lots of changes to the services and the scheduled tasks etc. on it. Default location.

**Comment by Fleex255** [comment]
Thank you for the details. There were indeed some problems here, which should be fixed in https://github.com/Fleex255/PolicyPlus/commit/a67e5d826571bcd38ea9a2c9c9fe8a9866b83b53. At your convenience, please try the [updated dev build](https://s3-us-west-2.amazonaws.com/policy-plus/PolicyPlusDev.exe) and let me know if that works for you,

**Comment by zdat** [comment]
Yes, this worked. Just posted a new issue though about something that randomly happened today.
