### ISSUE TITLE
How to verify the authenticity and integrity of builds from Release and S3 Bucket pages?

### ISSUE THREAD

**Issue by demosn01** [Fleex255/PolicyPlus#65]
Hi @Fleex255,

First of all, thank you for developing and maintaining PolicyPlus.

While reading through [issue #49](https://github.com/Fleex255/PolicyPlus/issues/49), I noticed that the GitHub `Actions` logs for the "compute hash" step have expired and are no longer available. I might be looking in the wrong place, or perhaps I'm missing a step. Here's an example URL:

```
https://github.com/Fleex255/PolicyPlus/actions/runs/2423806010/jobs/3674388980
```

Could you please guide me on how to verify the build, or suggest any alternative methods for verifying the authenticity and integrity of the downloaded build from your S3 bucket or builds on the Release page?

Thank you!

**Comment by Fleex255** [comment]
You're looking in the right place. Unfortunately, it seems GitHub Actions removes the logs after some time, and since I haven't made any code changes in a while, there aren't any available logs. I just enabled manual Actions runs so I can, if necessary, produce a new verified build in the future. [Here is today's log.](https://github.com/Fleex255/PolicyPlus/actions/runs/4520927778/jobs/7962352280)

Relevant GitHub feature request: [Always keep last workflow run log](https://github.com/orgs/community/discussions/17672).

**Comment by demosn01** [comment]
Thank you! Much appreciated
