### ISSUE TITLE
Vanity link for Releases (too).

### ISSUE THREAD

**Issue by rokejulianlockhart** [Fleex255/PolicyPlus#71]
We've already https://s3-us-west-2.amazonaws.com/policy-plus/PolicyPlusLatest.exe (per https://github.com/Fleex255/PolicyPlus#download) but we don't have one for https://github.com/Fleex255/PolicyPlus/releases/. This is problematic for things like https://github.com/microsoft/winget-pkgs/issues/112057#issue-1803179354. KDE generates vanity links for every type of release, and they're great for packaging efforts.

**Comment by Fleex255** [comment]
I've removed the "pre-release" mark from the last release so that the [GitHub latest-release link format](https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases#linking-to-the-latest-release) will work: https://github.com/Fleex255/PolicyPlus/releases/latest/download/PolicyPlus.exe

Going forward, I'll leave the pre-release box unchecked so that the above link will point to the latest GitHub release.

**Comment by RokeJulianLockhart** [comment]
@Fleex255, in retrospect, `/latest` might have already provided this, too. Apologies if so.
