### ISSUE TITLE
Imported .pol doesn't seem to change anything?

### ISSUE THREAD

**Issue by zdat** [Fleex255/PolicyPlus#86]
Export the .pol > change 1 policy > import the .pol, and it doesn't revert what I just changed.

Also importing / running the .reg file doesn't seem to change it either, at least as far as Policy Plus shows.

It's the case on 2 machines. Importing the .pol did seem to work some months ago when PolicyPlus was "fresh", but now no. Maybe because it already had a .pol imported to it?

Any help? Thanks.

**Comment by zdat** [comment]
It seem this only happens when I try to change something from an active state (Enabled or Disabled) > Not Configured.

So basically you can't overwrite "Enabled"/"Disabled" with "Not configured" with a .pol/.reg import. Can this be fixed?

**Comment by Fleex255** [comment]
Thanks for determining that only changing to Not Configured does nothing. Due to how Windows POL and REG files work, this is expected. Not Configured is the *absence* of any value in a Group Policy Object (POL) or the Registry. That is, there is no difference between setting a policy to Not Configured and not choosing a setting for it.

Importing Not Configured policies would be equivalent to totally replacing the target policy object with the imported POL. If that is what you want, you can use *File | Edit Raw POL* to forget everything in the existing POL before importing the new one.

If you want to semi-automate setting specific policies to Not Configured, please use Semantic Policy (SPOL), which is a more expressive format than Windows POL or REG.
